=== CarlosJOcasio/QA.Web.Automation/src/main/java/schema/rsi.default.selenium.schema.json
{
  "id": "https://ruralsourcing.com/test.cases.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Selenium data driven test.",
  "type": "object",
  "required": [ "browsers", "url", "steps", "closeBrowser" ],
  "properties": {
    "testCase": {
      "description":"Test case description.",
      "type":"string"
    },
    "browsers": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/browser"
      }
    },
    "url": {
      "description":"Url to open on the given browser.",
      "type": "string"
    },
    "steps": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/step"
      }
    },
    "snippet": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/snippet"
      }
    },
    "closeBrowser": {
      "description": "Close browser",
      "type": "string"
    }
  },
  "definitions": {
    "step": {
      "type": "object",
      "required": [
        "description",
        "name"
      ],
      "properties": {
        "name": {
          "type":"string",
          "description": "Step name."
        },
        "description": {
          "type":"string",
          "description": "Short description of what the tester is doing."
        },
        "locatorType": {
          "type": "string",
          "description": "Choose any of the locators type to located the element. id, name, cssSelector, xpath, tagName, linkText."
        },
        "locator": {
          "type": "string",
          "description": "Elements' locator string, make sure it match the locator type."
        },
        "value": {
          "type": "string",
          "description": "Value given by the user to verify and compare."
        }
      }
    },
    "browser": {
      "type": "object",
      "required": [
        "name",
        "runType"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the browser to test."
        },
        "runType": {
          "type": "string",
          "description": "Browser type."
        }
      }
    },
    "snippet": {
      "type": "string",
      "required": ["filePath"],
      "properties": {
        "filePath": {
          "type": "string",
          "description": "Path to snippet to load, file extension *.snippet.json."
        }
      }
    }
  }
}

=== CarlosJOcasio/QA.Web.Automation/src/main/java/inc/rsi/qe/schemas/rsi.site.address.test.json
{
  "testCase": "Test RSI ABQ Address.",
  "browsers": [
    {
      "name": "chrome",
      "runType": "faster"
    }
  ],
  "url": "http://ruralsourcing.com",
  "steps": [
    {
      "description": "Open 'About Us' link from the menu bar.",
      "name": "clickNavigatorLink",
      "locatorType": "cssSelector;cssSelector",
      "locator": "#mobile-navigation-trigger > span;#menu-item-8094 > a"
    },
    {
      "description": "Click 'OUR DEVELOPMENT CENTERS' button in 'About' page.",
      "name": "click",
      "locatorType": "cssSelector",
      "locator": "#starts-and-stays > div.row.align-middle > div.columns.small-12.medium-7.large-4.large-offset-2.small-order-2.medium-order-1 > div > div > a"
    },
    {
      "description": "Click 'New Mexico' button.",
      "name": "click",
      "locatorType": "cssSelector",
      "locator": "#rk1pmx-magellan > li:nth-child(4) > a"
    },
    {
      "description": "Get the Albuquerque, New Mexico's address and compare.",
      "name": "compareEqual",
      "locatorType": "cssSelector",
      "locator": "#rk1pmx-magellan > li:nth-child(4) > a",
      "value": "723 Silver Ave SW\nAlbuquerque, NM 87102\n505.218.8500"
    }
  ],
  "closeBrowser": "Close the browser."
}

=== CarlosJOcasio/QA.Web.Automation/src/main/java/com/google/qe/schemas/google.site.rsi.search.test.json
{
  "testCase": "Test RSI website Google search.",
  "browsers": [
    {
      "name": "chrome",
      "runType": "faster"
    }
  ],
  "url": "http://google.com",
  "steps": [
    {
      "description": "Enter RSIs company name in google's main text box.",
      "name": "enterText",
      "locatorType": "id",
      "locator": "lst-ib",
      "value":"Rural Sourcing Inc."
    },
    {
      "description": "Click on Google Search button.",
      "name": "click",
      "locatorType": "cssSelector",
      "locator": "#sbtc > div.gstl_0.sbdd_a > div:nth-child(2) > div.sbdd_b > div > ul > li:nth-child(11) > div > span:nth-child(1) > span > input"
    },
    {
      "description": "Click Rural Sourcing - America's leading provider of domestic outsourced IT link.",
      "name": "click",
      "locatorType": "linkText",
      "locator": "Rural Sourcing - America's leading provider of domestic outsourced IT"
    },
    {
      "description": "Validate Page Title Rural Sourcing - America's leading provider of domestic outsourced IT link.",
      "name": "validateTitle",
      "value": "Rural Sourcing - Americaâ€™s leading provider of domestic outsourced IT"
    }
  ],
  "closeBrowser": "Close the browser."
}
